server:
  port: "8080"
  host: "localhost"
  read_timeout: 30
  write_timeout: 30

database:
  type: "mysql"  # or "postgres"
  host: "mysql"  # Use container name for Docker networking
  port: 3306
  username: "loguser"  # Match docker-compose credentials
  password: "logpass"  # Match docker-compose credentials
  database: "log_analyzer"
  ssl_mode: "disable"

logging:
  level: "info"
  output_file: "logs/app.log"
  max_size: 100
  max_backups: 3
